"""
Configuration for CPG RAG Complete Pipeline
"""
import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()


class Config:
    """Central configuration for the CPG RAG system."""
    
    # --- Disable ChromaDB telemetry globally ---
    TELEMETRY_DISABLE = True
    if TELEMETRY_DISABLE:
        # Completely silence all Chroma/PostHog telemetry noise
        os.environ["CHROMA_TELEMETRY_ENABLED"] = "false"
        os.environ["ANONYMIZED_TELEMETRY"] = "false"
        os.environ["POSTHOG_API_KEY"] = ""
        os.environ["POSTHOG_DISABLED"] = "true"

    # Paths
    BASE_DIR = Path(__file__).parent
    DATA_DIR = BASE_DIR / "data"
    OUTPUT_DIR = BASE_DIR / "output"
    CHROMA_DIR = BASE_DIR / "chroma_db"
    
    # CPG files (generated by extract_cpg.py)
    CPG_NODES_FILE = DATA_DIR / "cpg_nodes.json"
    CPG_EDGES_FILE = DATA_DIR / "cpg_edges.json"
    METHODS_FILE = DATA_DIR / "methods.json"
    CALLS_FILE = DATA_DIR / "calls.json"
    STATS_FILE = DATA_DIR / "codebase_stats.json"
    
    # Ollama settings
    OLLAMA_BASE_URL = os.getenv('OLLAMA_BASE_URL', 'http://localhost:11434')
    OLLAMA_MODEL = os.getenv('OLLAMA_MODEL', 'llama3.2')
    OLLAMA_EMBEDDING_MODEL = os.getenv('OLLAMA_EMBEDDING_MODEL', 'nomic-embed-text')
    OLLAMA_TEMPERATURE = float(os.getenv('OLLAMA_TEMPERATURE', '0'))
    
    # Neo4j settings (optional)
    NEO4J_URI = os.getenv('NEO4J_URI', 'bolt://localhost:7687')
    NEO4J_USER = os.getenv('NEO4J_USER', 'neo4j')
    NEO4J_PASSWORD = os.getenv('NEO4J_PASSWORD', 'cpgragagent123')
    
    # Chroma collections
    SEMANTIC_COLLECTION = 'cpg_semantic'
    STRUCTURAL_COLLECTION = 'cpg_structural'
    FAULT_COLLECTION = 'cpg_fault'
    HYBRID_COLLECTION = 'cpg_hybrid'

    # RAG settings
    TOP_K_RESULTS = 5
    GRAPH_DEPTH = int(os.getenv("GRAPH_DEPTH", 3))
    GRAPH_CONTEXT_DEPTH = GRAPH_DEPTH
    MAX_CONTEXT_NODES = 10
    MAX_CODE_LENGTH = 1200  # Max characters of code to include in context
    
    # Joern settings
    JOERN_CLI_PATH = os.getenv('JOERN_CLI_PATH', '')

    @classmethod
    def ensure_directories(cls):
        """Create necessary directories if they don't exist."""
        cls.DATA_DIR.mkdir(parents=True, exist_ok=True)
        cls.OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
        cls.CHROMA_DIR.mkdir(parents=True, exist_ok=True)
    
    @classmethod
    def print_config(cls):
        """Print current configuration."""
        print("=" * 60)
        print("CPG RAG Configuration")
        print("=" * 60)
        print(f"  Base Directory: {cls.BASE_DIR}")
        print(f"  Data Directory: {cls.DATA_DIR}")
        print(f"  Output Directory: {cls.OUTPUT_DIR}")
        print(f"  ChromaDB Directory: {cls.CHROMA_DIR}")
        print()
        print(f"  Ollama URL: {cls.OLLAMA_BASE_URL}")
        print(f"  Ollama Model: {cls.OLLAMA_MODEL}")
        print(f"  Embedding Model: {cls.OLLAMA_EMBEDDING_MODEL}")
        print()
        print(f"  Neo4j URI: {cls.NEO4J_URI}")
        print()
        print(f"  Graph Depth: {cls.GRAPH_DEPTH}")
        print(f"  Hybrid Collection: {cls.HYBRID_COLLECTION}")
        print(f"  Telemetry Disabled: {cls.TELEMETRY_DISABLE}")
        print("=" * 60)
